#!/usr/bin/env python3
"""
Spread Capture Strategy Simulator

Tests the continuous velocity market maker (spread_capture.py) using real-time data.
Records hypothetical trading activity WITHOUT placing real orders.

Key Differences from calc_maker_velocity_sim.py:
- Continuous two-sided quoting (vs sequential entry→hedge)
- Grid orders at multiple price levels
- Inventory management with 10% max imbalance
- Velocity-based quote ADJUSTMENT (not gating)

Expected Results:
- Cycles/hour: 50-100 (vs 5.6 with old velocity gating)
- Fill rate: 80%+ (vs 12.7% with old approach)
- Profit/hour: $20-40 (vs $3.22 with old approach)

Usage:
    python scripts/spread_capture_sim.py --hours 2 --output research/
    python scripts/spread_capture_sim.py --hours 0.1  # Quick 6-min test
"""

import argparse
import asyncio
import csv
import sys
import os
import random
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any, List
import time
import logging

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.config import Config
from src.api.binance_client import BinanceClient
from src.api.websocket_client import WebSocketClient, BookUpdate
from src.services.market_finder import MarketFinder
from src.services.trend_detector import TrendDetector
from src.models.market import BTCMarket
from src.strategies.spread_capture import SpreadCaptureStrategy

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)


# =============================================================================
# CONSTANTS
# =============================================================================
FILL_PROB_BASE = 0.03           # Base fill probability per 100ms
FILL_PROB_TIGHT = 0.06          # Fill probability for tight quotes
FILL_PROB_WIDE = 0.015          # Fill probability for wide quotes
MARKET_DURATION = 900           # 15-minute markets
QUOTE_INTERVAL = 0.5            # Generate quotes every 500ms
GATE_DURATION = 5.0             # Wait 5s at market open


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class SimulatedQuote:
    """Records a quote generated by the strategy."""
    timestamp: float
    market_slug: str
    side: str
    price: float
    size: int
    level: int
    velocity_bps: float
    up_offset: float
    down_offset: float
    is_rebalance: bool


@dataclass
class SimulatedFill:
    """Records a simulated fill."""
    timestamp: float
    market_slug: str
    side: str
    price: float
    size: int
    level: int
    velocity_at_fill: float
    time_to_fill_ms: float
    was_rebalance: bool


@dataclass
class MarketSession:
    """Records one complete market session."""
    market_slug: str
    start_time: float
    end_time: float

    # Fills
    up_fills: int
    down_fills: int
    up_volume: float
    down_volume: float
    up_avg_price: float
    down_avg_price: float

    # Performance
    pairs_matched: int
    pair_cost: float
    profit: float
    profit_dollars: float

    # Statistics
    quotes_generated: int
    fills_count: int
    fill_rate_pct: float
    rebalance_count: int
    max_imbalance_pct: float

    # Velocity stats
    avg_velocity: float
    velocity_aligned_fills: int  # Fills where velocity favored the side


@dataclass
class VelocitySample:
    """Records velocity and quote state at a point in time."""
    timestamp: float
    market_slug: str
    btc_price: float
    velocity_bps: float
    up_ask: float
    down_ask: float
    up_bid: float
    down_bid: float
    up_offset: float
    down_offset: float
    up_shares: int
    down_shares: int
    imbalance_pct: float


# =============================================================================
# SIMULATOR CLASS
# =============================================================================

class SpreadCaptureSim:
    """
    Simulates spread capture strategy with continuous velocity quoting.

    Uses real Polymarket orderbook + Binance prices, simulates fills.
    """

    def __init__(self, output_dir: str = "research/"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Strategy - use the new continuous velocity MM
        self.strategy = SpreadCaptureStrategy(
            base_size=10,
            target_shares=100,
            grid_levels=3,
            max_imbalance_pct=0.10,
        )

        # Clients
        self.binance_client: Optional[BinanceClient] = None
        self.ws_client: Optional[WebSocketClient] = None
        self.trend_detector: Optional[TrendDetector] = None
        self.market_finder: Optional[MarketFinder] = None

        # Current market
        self.current_market: Optional[BTCMarket] = None
        self.strike_price: float = 0.0

        # Orderbook cache
        self._up_book: Optional[BookUpdate] = None
        self._down_book: Optional[BookUpdate] = None

        # Tracking
        self.quotes: List[SimulatedQuote] = []
        self.fills: List[SimulatedFill] = []
        self.market_sessions: List[MarketSession] = []
        self.velocity_samples: List[VelocitySample] = []

        # Current session tracking
        self._session_start: float = 0.0
        self._session_quotes: int = 0
        self._session_fills: int = 0
        self._session_max_imbalance: float = 0.0
        self._velocity_sums: float = 0.0
        self._velocity_count: int = 0
        self._aligned_fills: int = 0

        # Pending orders (simulated order book)
        self._pending_orders: Dict[str, Dict[str, Any]] = {}  # order_id -> order
        self._order_counter: int = 0

        # State
        self._ws_task: Optional[asyncio.Task] = None
        self._last_sample_time: float = 0.0

        # Incremental save
        self._run_timestamp: str = datetime.now().strftime("%Y%m%d_%H%M%S")
        self._fills_csv_path: Optional[Path] = None

    def _on_book_update(self, update: BookUpdate):
        """Callback for WebSocket book updates."""
        if not self.current_market:
            return

        if update.token_id == self.current_market.up_token_id:
            self._up_book = update
        elif update.token_id == self.current_market.down_token_id:
            self._down_book = update

    def _get_velocity(self) -> float:
        """Get current velocity from trend detector."""
        if not self.trend_detector:
            return 0.0
        signal = self.trend_detector.get_trend_signal()
        return signal.velocity_bps if signal else 0.0

    def _get_orderbook_prices(self) -> tuple[float, float, float, float]:
        """Get current orderbook prices."""
        up_ask = self._up_book.best_ask if self._up_book and self._up_book.best_ask else 0.50
        down_ask = self._down_book.best_ask if self._down_book and self._down_book.best_ask else 0.50
        up_bid = self._up_book.best_bid if self._up_book and self._up_book.best_bid else 0.49
        down_bid = self._down_book.best_bid if self._down_book and self._down_book.best_bid else 0.49
        return up_ask, down_ask, up_bid, down_bid

    def _record_velocity_sample(self):
        """Record velocity sample every second."""
        now = time.time()
        if now - self._last_sample_time < 1.0:
            return
        self._last_sample_time = now

        if not self.current_market:
            return

        up_ask, down_ask, up_bid, down_bid = self._get_orderbook_prices()
        velocity = self._get_velocity()

        status = self.strategy.get_status()

        self.velocity_samples.append(VelocitySample(
            timestamp=now,
            market_slug=self.current_market.slug,
            btc_price=self.binance_client.current_price if self.binance_client else 0,
            velocity_bps=velocity,
            up_ask=up_ask,
            down_ask=down_ask,
            up_bid=up_bid,
            down_bid=down_bid,
            up_offset=status["last_offsets"]["up"],
            down_offset=status["last_offsets"]["down"],
            up_shares=status["position"]["up_shares"],
            down_shares=status["position"]["down_shares"],
            imbalance_pct=status["position"]["imbalance_pct"],
        ))

        # Track max imbalance in session
        imbalance_pct = status["position"]["imbalance_pct"]
        if imbalance_pct > self._session_max_imbalance:
            self._session_max_imbalance = imbalance_pct

    def _save_fill_incremental(self, fill: SimulatedFill):
        """Save fill to CSV immediately."""
        if self._fills_csv_path is None:
            self._fills_csv_path = self.output_dir / f"spread_capture_fills_{self._run_timestamp}.csv"
            with open(self._fills_csv_path, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow([
                    'timestamp', 'market_slug', 'side', 'price', 'size', 'level',
                    'velocity_bps', 'time_to_fill_ms', 'was_rebalance'
                ])
            logger.info(f"[SAVE] Created fills CSV: {self._fills_csv_path}")

        with open(self._fills_csv_path, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                fill.timestamp, fill.market_slug, fill.side, fill.price,
                fill.size, fill.level, fill.velocity_at_fill,
                fill.time_to_fill_ms, fill.was_rebalance
            ])

    async def initialize(self):
        """Initialize all clients."""
        logger.info("Initializing Spread Capture Simulator...")

        # Binance client
        self.binance_client = BinanceClient()
        await self.binance_client.connect()

        logger.info("Waiting for Binance WebSocket...")
        for _ in range(100):
            if self.binance_client.is_connected and self.binance_client.current_price > 0:
                break
            await asyncio.sleep(0.1)

        if not self.binance_client.is_connected:
            raise RuntimeError("Failed to connect to Binance WebSocket")

        logger.info(f"Binance connected! BTC: ${self.binance_client.current_price:,.2f}")

        # Trend detector
        self.trend_detector = TrendDetector(self.binance_client)

        # Market finder
        self.market_finder = MarketFinder()

        # Polymarket WebSocket
        self.ws_client = WebSocketClient(auto_reconnect=True)
        self.ws_client.on_book_update(self._on_book_update)

        logger.info("Simulator initialized.")

    async def find_active_market(self) -> Optional[BTCMarket]:
        """Find current active BTC 15-min market."""
        market = await self.market_finder.get_current_market()
        if market and market.time_remaining() > 60:
            return market

        markets = await self.market_finder.get_current_and_upcoming_markets(count=3)
        for m in markets:
            if m.is_active() and m.time_remaining() > 60:
                return m

        return markets[0] if markets else None

    def _calculate_fill_probability(self, quote: Dict[str, Any], book: Optional[BookUpdate]) -> float:
        """
        Calculate fill probability for a quote.

        Higher probability when:
        - Quote price is closer to best_ask
        - Quote is at level 0 (best price)
        - Rebalance orders (tighter spread)
        """
        if not book or not book.best_ask:
            return FILL_PROB_BASE

        distance_to_ask = book.best_ask - quote['price']

        if distance_to_ask < 0:
            # Quote at or above ask = instant fill
            return 1.0

        if distance_to_ask <= 0.01:  # Within 1 cent
            base_prob = FILL_PROB_TIGHT
        elif distance_to_ask <= 0.02:  # Within 2 cents
            base_prob = FILL_PROB_BASE
        else:
            base_prob = FILL_PROB_WIDE

        # Level 0 orders more likely to fill
        if quote.get('level', 0) == 0:
            base_prob *= 1.5

        # Rebalance orders (tighter spread) more aggressive
        if quote.get('is_rebalance', False):
            base_prob *= 1.3

        return min(0.5, base_prob)  # Cap at 50% per tick

    async def _process_quotes(self, quotes: List[Dict[str, Any]]) -> None:
        """
        Process quotes and simulate fills.

        For each quote:
        1. Check if order already pending at this price
        2. If not, add to pending orders
        3. For pending orders, check fill probability
        4. Record fills
        """
        if not self.current_market:
            return

        velocity = self._get_velocity()
        now = time.time()

        # Record quotes
        status = self.strategy.get_status()
        for q in quotes:
            self.quotes.append(SimulatedQuote(
                timestamp=now,
                market_slug=self.current_market.slug,
                side=q['side'],
                price=q['price'],
                size=q['size'],
                level=q.get('level', 0),
                velocity_bps=velocity,
                up_offset=status["last_offsets"]["up"],
                down_offset=status["last_offsets"]["down"],
                is_rebalance=q.get('is_rebalance', False),
            ))
            self._session_quotes += 1

            # Add to pending orders (simplified - just track newest at each price level)
            order_key = f"{q['side']}_{q['price']:.2f}_{q.get('level', 0)}"
            self._pending_orders[order_key] = {
                **q,
                'placed_at': now,
                'velocity_at_place': velocity,
            }

        # Process pending orders for fills
        filled_keys = []
        for key, order in self._pending_orders.items():
            book = self._up_book if order['side'] == "UP" else self._down_book
            fill_prob = self._calculate_fill_probability(order, book)

            if random.random() < fill_prob:
                # Fill!
                fill_time = time.time()
                time_to_fill = (fill_time - order['placed_at']) * 1000

                fill = SimulatedFill(
                    timestamp=fill_time,
                    market_slug=self.current_market.slug,
                    side=order['side'],
                    price=order['price'],
                    size=order['size'],
                    level=order.get('level', 0),
                    velocity_at_fill=velocity,
                    time_to_fill_ms=time_to_fill,
                    was_rebalance=order.get('is_rebalance', False),
                )

                self.fills.append(fill)
                self._save_fill_incremental(fill)
                self._session_fills += 1

                # Notify strategy
                self.strategy.on_fill(order['side'], order['price'], order['size'])

                # Track velocity alignment
                velocity_favors = (velocity > 0.05 and order['side'] == "UP") or \
                                 (velocity < -0.05 and order['side'] == "DOWN")
                if velocity_favors:
                    self._aligned_fills += 1

                logger.info(
                    f"[FILL] {order['side']} {order['size']}@${order['price']:.3f} "
                    f"in {time_to_fill:.0f}ms (vel={velocity:.3f}bps)"
                )

                filled_keys.append(key)

        # Remove filled orders
        for key in filled_keys:
            del self._pending_orders[key]

        # Expire old orders (>30s)
        expired_keys = [
            k for k, v in self._pending_orders.items()
            if now - v['placed_at'] > 30.0
        ]
        for key in expired_keys:
            del self._pending_orders[key]

    def _start_session(self):
        """Start tracking a new market session."""
        self._session_start = time.time()
        self._session_quotes = 0
        self._session_fills = 0
        self._session_max_imbalance = 0.0
        self._velocity_sums = 0.0
        self._velocity_count = 0
        self._aligned_fills = 0
        self._pending_orders.clear()
        self.strategy.reset()

    def _end_session(self):
        """End current session and record stats."""
        if not self.current_market:
            return

        status = self.strategy.get_status()
        pos = status["position"]
        stats = status["statistics"]

        session = MarketSession(
            market_slug=self.current_market.slug,
            start_time=self._session_start,
            end_time=time.time(),
            up_fills=stats["total_up_fills"],
            down_fills=stats["total_down_fills"],
            up_volume=pos["up_shares"] * pos["up_avg_price"] if pos["up_shares"] > 0 else 0,
            down_volume=pos["down_shares"] * pos["down_avg_price"] if pos["down_shares"] > 0 else 0,
            up_avg_price=pos["up_avg_price"],
            down_avg_price=pos["down_avg_price"],
            pairs_matched=stats["total_pairs_matched"],
            pair_cost=pos["pair_cost"],
            profit=stats["total_profit"],
            profit_dollars=stats["total_profit"] * stats["total_pairs_matched"] if stats["total_pairs_matched"] > 0 else 0,
            quotes_generated=self._session_quotes,
            fills_count=self._session_fills,
            fill_rate_pct=100 * self._session_fills / max(1, self._session_quotes),
            rebalance_count=stats["rebalance_count"],
            max_imbalance_pct=self._session_max_imbalance,
            avg_velocity=self._velocity_sums / max(1, self._velocity_count),
            velocity_aligned_fills=self._aligned_fills,
        )

        self.market_sessions.append(session)

        logger.info(
            f"[SESSION] {session.market_slug}: "
            f"fills={session.fills_count}/{session.quotes_generated} ({session.fill_rate_pct:.1f}%), "
            f"pairs={session.pairs_matched}, profit=${session.profit:.4f}"
        )

    async def _rotate_market_if_needed(self) -> bool:
        """Check if market expired and rotate."""
        if not self.current_market:
            return False

        time_left = self.current_market.time_remaining()
        if time_left > 30:
            return False

        logger.info(f"[ROTATION] Market expiring: {self.current_market.slug}")

        # End current session
        self._end_session()

        # Find new market
        new_market = await self.find_active_market()
        if not new_market or new_market.slug == self.current_market.slug:
            logger.info("[ROTATION] No new market yet, waiting...")
            return False

        # Rotate
        self.current_market = new_market
        self.strike_price = self.binance_client.current_price
        self.binance_client.set_strike_price(self.strike_price)

        # Clear orderbook
        self._up_book = None
        self._down_book = None

        # Reconnect WebSocket
        if self._ws_task:
            self._ws_task.cancel()
            try:
                await self._ws_task
            except asyncio.CancelledError:
                pass

        await self.ws_client.disconnect()
        if not await self.ws_client.connect():
            logger.error("[ROTATION] Failed to reconnect WebSocket!")
            return False

        token_ids = [self.current_market.up_token_id, self.current_market.down_token_id]
        if not await self.ws_client.subscribe(token_ids):
            logger.error("[ROTATION] Failed to subscribe!")
            return False

        self._ws_task = asyncio.create_task(self.ws_client.run())

        # Wait for orderbook
        for _ in range(50):
            if self._up_book and self._down_book:
                break
            await asyncio.sleep(0.1)

        # Start new session
        self._start_session()
        logger.info(f"[ROTATION] New market: {new_market.slug}")

        return True

    async def run(self, hours: float = 2.0):
        """Run simulation for specified hours."""
        end_time = time.time() + (hours * 3600)

        logger.info(f"\n{'#'*60}")
        logger.info(f"# SPREAD CAPTURE STRATEGY SIMULATOR")
        logger.info(f"# Duration: {hours} hours")
        logger.info(f"# Strategy: Continuous Velocity MM")
        logger.info(f"# Output: {self.output_dir}")
        logger.info(f"{'#'*60}\n")

        await self.initialize()

        # Find active market
        self.current_market = await self.find_active_market()
        if not self.current_market:
            logger.error("No active market found!")
            return

        self.strike_price = self.binance_client.current_price
        self.binance_client.set_strike_price(self.strike_price)

        logger.info(f"Market: {self.current_market.slug}")
        logger.info(f"Strike: ${self.strike_price:,.2f}")
        logger.info(f"Time remaining: {self.current_market.time_remaining():.0f}s")

        # Connect WebSocket
        if not await self.ws_client.connect():
            logger.error("Failed to connect WebSocket!")
            return

        token_ids = [self.current_market.up_token_id, self.current_market.down_token_id]
        if not await self.ws_client.subscribe(token_ids):
            logger.error("Failed to subscribe!")
            return

        self._ws_task = asyncio.create_task(self.ws_client.run())

        # Wait for orderbook
        for _ in range(50):
            if self._up_book and self._down_book:
                break
            await asyncio.sleep(0.1)

        # Start first session
        self._start_session()

        last_market_check = 0.0

        try:
            while time.time() < end_time:
                now = time.time()

                # Record velocity sample
                self._record_velocity_sample()

                # Track velocity for averaging
                velocity = self._get_velocity()
                self._velocity_sums += abs(velocity)
                self._velocity_count += 1

                # Check market rotation
                if now - last_market_check > 10.0:
                    await self._rotate_market_if_needed()
                    last_market_check = now

                # Wait at market open
                time_remaining = self.current_market.time_remaining() if self.current_market else 0
                time_elapsed = 900 - time_remaining

                if time_elapsed < GATE_DURATION:
                    await asyncio.sleep(0.5)
                    continue

                # Skip if <60s remaining
                if time_remaining < 60:
                    await asyncio.sleep(0.5)
                    continue

                # Generate quotes
                if self._up_book and self._down_book:
                    up_ask, down_ask, up_bid, down_bid = self._get_orderbook_prices()

                    quotes = self.strategy.get_quotes(
                        up_bid=up_bid,
                        up_ask=up_ask,
                        down_bid=down_bid,
                        down_ask=down_ask,
                        velocity_bps=velocity,
                        time_remaining=time_remaining,
                    )

                    if quotes:
                        await self._process_quotes(quotes)

                await asyncio.sleep(QUOTE_INTERVAL)

        except KeyboardInterrupt:
            logger.info("\nSimulation interrupted by user")
        finally:
            # End current session
            self._end_session()

            # Cleanup
            if self._ws_task:
                self._ws_task.cancel()
            if self.ws_client:
                await self.ws_client.disconnect()
            if self.binance_client:
                await self.binance_client.disconnect()

        # Write results
        self._write_results()

    def _write_results(self):
        """Write CSVs and print summary."""
        timestamp = self._run_timestamp

        # Sessions CSV
        sessions_path = self.output_dir / f"spread_capture_sessions_{timestamp}.csv"
        with open(sessions_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                'market_slug', 'start_time', 'end_time',
                'up_fills', 'down_fills', 'up_avg_price', 'down_avg_price',
                'pairs_matched', 'pair_cost', 'profit', 'profit_dollars',
                'quotes_generated', 'fills_count', 'fill_rate_pct',
                'rebalance_count', 'max_imbalance_pct',
                'avg_velocity', 'velocity_aligned_fills'
            ])
            for s in self.market_sessions:
                writer.writerow([
                    s.market_slug, s.start_time, s.end_time,
                    s.up_fills, s.down_fills, s.up_avg_price, s.down_avg_price,
                    s.pairs_matched, s.pair_cost, s.profit, s.profit_dollars,
                    s.quotes_generated, s.fills_count, s.fill_rate_pct,
                    s.rebalance_count, s.max_imbalance_pct,
                    s.avg_velocity, s.velocity_aligned_fills
                ])

        # Velocity time series CSV
        velocity_path = self.output_dir / f"spread_capture_velocity_{timestamp}.csv"
        with open(velocity_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                'timestamp', 'market_slug', 'btc_price', 'velocity_bps',
                'up_ask', 'down_ask', 'up_bid', 'down_bid',
                'up_offset', 'down_offset', 'up_shares', 'down_shares', 'imbalance_pct'
            ])
            for v in self.velocity_samples:
                writer.writerow([
                    v.timestamp, v.market_slug, v.btc_price, v.velocity_bps,
                    v.up_ask, v.down_ask, v.up_bid, v.down_bid,
                    v.up_offset, v.down_offset, v.up_shares, v.down_shares, v.imbalance_pct
                ])

        # Print summary
        print(f"\n{'='*60}")
        print(f"SPREAD CAPTURE STRATEGY SIMULATION RESULTS")
        print(f"{'='*60}")

        if not self.market_sessions:
            print("No market sessions completed.")
            return

        n = len(self.market_sessions)
        total_fills = sum(s.fills_count for s in self.market_sessions)
        total_quotes = sum(s.quotes_generated for s in self.market_sessions)
        total_pairs = sum(s.pairs_matched for s in self.market_sessions)
        total_profit = sum(s.profit for s in self.market_sessions)

        avg_fill_rate = sum(s.fill_rate_pct for s in self.market_sessions) / n

        # Time-based metrics
        total_duration_hours = sum(
            (s.end_time - s.start_time) for s in self.market_sessions
        ) / 3600

        fills_per_hour = total_fills / max(0.01, total_duration_hours)
        pairs_per_hour = total_pairs / max(0.01, total_duration_hours)
        profit_per_hour = total_profit / max(0.01, total_duration_hours)

        print(f"Duration: {total_duration_hours:.2f} hours across {n} markets")
        print(f"")
        print(f"FILL STATISTICS:")
        print(f"  Total quotes generated: {total_quotes}")
        print(f"  Total fills: {total_fills}")
        print(f"  Overall fill rate: {100 * total_fills / max(1, total_quotes):.1f}%")
        print(f"  Avg session fill rate: {avg_fill_rate:.1f}%")
        print(f"  Fills/hour: {fills_per_hour:.1f}")
        print(f"")
        print(f"PROFIT SUMMARY:")
        print(f"  Total pairs matched: {total_pairs}")
        print(f"  Total profit: ${total_profit:.4f}")
        print(f"  Pairs/hour: {pairs_per_hour:.1f}")
        print(f"  Profit/hour: ${profit_per_hour:.4f}")
        print(f"")

        # Velocity statistics
        aligned_fills = sum(s.velocity_aligned_fills for s in self.market_sessions)
        print(f"VELOCITY EFFECTIVENESS:")
        print(f"  Velocity-aligned fills: {aligned_fills}/{total_fills} ({100 * aligned_fills / max(1, total_fills):.1f}%)")
        print(f"")

        # Imbalance/rebalance stats
        total_rebalances = sum(s.rebalance_count for s in self.market_sessions)
        max_imbalance = max(s.max_imbalance_pct for s in self.market_sessions) if self.market_sessions else 0
        print(f"INVENTORY MANAGEMENT:")
        print(f"  Total rebalances: {total_rebalances}")
        print(f"  Max imbalance observed: {max_imbalance:.1%}")
        print(f"")

        # Comparison with old strategy
        print(f"COMPARISON WITH OLD VELOCITY-GATED STRATEGY:")
        print(f"  Old fills/hour: ~5.6 → New: {fills_per_hour:.1f} ({fills_per_hour/5.6:.1f}x improvement)")
        print(f"  Old fill rate: ~12.7% → New: {avg_fill_rate:.1f}%")
        print(f"  Old profit/hour: ~$0.32 → New: ${profit_per_hour:.2f}")
        print(f"")

        print(f"OUTPUT FILES:")
        print(f"  Fills: {self._fills_csv_path}")
        print(f"  Sessions: {sessions_path}")
        print(f"  Velocity: {velocity_path}")
        print(f"{'='*60}\n")


# =============================================================================
# MAIN
# =============================================================================

async def main():
    parser = argparse.ArgumentParser(description='Spread Capture Strategy Simulator')
    parser.add_argument('--hours', type=float, default=2.0, help='Duration in hours (default: 2)')
    parser.add_argument('--output', type=str, default='research/', help='Output directory')
    args = parser.parse_args()

    sim = SpreadCaptureSim(output_dir=args.output)
    await sim.run(hours=args.hours)


if __name__ == "__main__":
    asyncio.run(main())
